--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/2/2023 9:53:40 AM
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE qvc_task_info;

--
-- Drop procedure `Proc_GetOne_Employee`
--
DROP PROCEDURE IF EXISTS Proc_GetOne_Employee;

--
-- Drop table `databaseinfo`
--
DROP TABLE IF EXISTS databaseinfo;

--
-- Drop procedure `Proc_GetAll_Employee`
--
DROP PROCEDURE IF EXISTS Proc_GetAll_Employee;

--
-- Drop procedure `Proc_GetByUserPass_Employee`
--
DROP PROCEDURE IF EXISTS Proc_GetByUserPass_Employee;

--
-- Drop procedure `Proc_GetUserByEmail_Employee`
--
DROP PROCEDURE IF EXISTS Proc_GetUserByEmail_Employee;

--
-- Drop procedure `Proc_Insert_Employee`
--
DROP PROCEDURE IF EXISTS Proc_Insert_Employee;

--
-- Drop procedure `Proc_UpdateByUserName_Employee`
--
DROP PROCEDURE IF EXISTS Proc_UpdateByUserName_Employee;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop procedure `Proc_GetByCode_Company`
--
DROP PROCEDURE IF EXISTS Proc_GetByCode_Company;

--
-- Drop procedure `Proc_Insert_Company`
--
DROP PROCEDURE IF EXISTS Proc_Insert_Company;

--
-- Drop table `company`
--
DROP TABLE IF EXISTS company;

--
-- Set default database
--
USE qvc_task_info;

--
-- Create table `company`
--
CREATE TABLE company (
  CompanyID char(36) NOT NULL DEFAULT '',
  CompanyCode varchar(128) NOT NULL DEFAULT '',
  CompanyName varchar(255) NOT NULL DEFAULT '',
  UserName varchar(100) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (CompanyID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1260,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin công ty';

--
-- Create index `CompanyCode` on table `company`
--
ALTER TABLE company
ADD UNIQUE INDEX CompanyCode (CompanyCode);

--
-- Create index `CompanyName` on table `company`
--
ALTER TABLE company
ADD UNIQUE INDEX CompanyName (CompanyName);

DELIMITER $$

--
-- Create procedure `Proc_Insert_Company`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Insert_Company (IN `@CompanyID` char(36), IN `@CompanyCode` varchar(128), IN `@CompanyName` varchar(255), IN `@UserName` varchar(100), IN `@CreatedDate` datetime, IN `@CreatedBy` varchar(100), IN `@ModifiedDate` datetime, IN `@ModifiedBy` varchar(100))
COMMENT 'Thêm mới công ty'
BEGIN
  INSERT INTO company (CompanyID, CompanyCode, CompanyName, UserName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy)
    VALUES (`@CompanyID`, `@CompanyCode`, `@CompanyName`, `@UserName`, `@CreatedDate`, `@CreatedBy`, `@ModifiedDate`, `@ModifiedBy`);
END
$$

--
-- Create procedure `Proc_GetByCode_Company`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetByCode_Company (IN `@CompanyCode` varchar(128))
COMMENT 'LẤy thông tin công ty từ mã công ty'
BEGIN
  SELECT
    *
  FROM company c
  WHERE c.CompanyCode = `@CompanyCode`;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL DEFAULT '',
  EmployeeCode varchar(20) NOT NULL DEFAULT '',
  EmployeeName varchar(100) NOT NULL DEFAULT '',
  UserName varchar(128) NOT NULL DEFAULT '',
  Password varchar(128) NOT NULL DEFAULT '',
  AccountType tinyint DEFAULT NULL COMMENT 'Trạng thái tài khoản; 0: Ngưng sử dụng; 1: Đang sử dụng; 2: Chưa xác minh',
  DateOfBirth date DEFAULT NULL,
  Gender tinyint DEFAULT NULL COMMENT 'Giới tính; 0: Nữ; 1: Nam; 2: Khác',
  Email varchar(100) DEFAULT NULL,
  PhoneNumber varchar(50) DEFAULT NULL,
  Address varchar(255) DEFAULT NULL,
  CompanyID char(36) DEFAULT NULL,
  DepartmentID char(36) DEFAULT NULL,
  PositionID char(36) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  Code int DEFAULT NULL COMMENT 'Mã xác thực tài khoản',
  Role int DEFAULT NULL,
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin nhân viên';

--
-- Create index `Email` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX Email (Email);

--
-- Create index `EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX EmployeeCode (EmployeeCode);

--
-- Create index `UserName` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX UserName (UserName);

DELIMITER $$

--
-- Create procedure `Proc_UpdateByUserName_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_UpdateByUserName_Employee (IN `@EmployeeID` char(36), IN `@EmployeeCode` varchar(20), IN `@EmployeeName` varchar(100), IN `@UserName` varchar(128), IN `@Password` varchar(128), IN `@AccountType` tinyint, IN `@DateOfBirth` date, IN `@Gender` tinyint, IN `@Email` varchar(100), IN `@PhoneNumber` varchar(50), IN `@Address` varchar(255), IN `@CompanyID` char(36), IN `@DepartmentID` char(36), IN `@PositionID` char(36), IN `@CreatedDate` datetime, IN `@CreatedBy` varchar(100), IN `@ModifiedDate` datetime, IN `@ModifiedBy` varchar(100), IN `@Code` int, IN `@Role` int)
BEGIN
  UPDATE employee e
  SET EmployeeCode = `@EmployeeCode`,
      EmployeeName = `@EmployeeName`,
      UserName = `@UserName`,
      Password = `@Password`,
      AccountType = `@AccountType`,
      DateOfBirth = `@DateOfBirth`,
      Gender = `@Gender`,
      Email = `@Email`,
      PhoneNumber = `@PhoneNumber`,
      Address = `@Address`,
      CompanyID = `@CompanyID`,
      DepartmentID = `@DepartmentID`,
      PositionID = `@PositionID`,
      ModifiedDate = `@ModifiedDate`,
      ModifiedBy = `@ModifiedBy`,
      Code = `@Code`,
      Role = `@Role`
  WHERE UserName = `@UserName`;
END
$$

--
-- Create procedure `Proc_Insert_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Insert_Employee (IN `@EmployeeID` char(36), IN `@EmployeeCode` varchar(20), IN `@EmployeeName` varchar(100), IN `@UserName` varchar(128), IN `@Password` varchar(128), IN `@AccountType` tinyint, IN `@DateOfBirth` date, IN `@Gender` tinyint, IN `@Email` varchar(100), IN `@PhoneNumber` varchar(50), IN `@Address` varchar(255), IN `@CompanyID` char(36), IN `@DepartmentID` char(36), IN `@PositionID` char(36), IN `@CreatedDate` datetime, IN `@CreatedBy` varchar(100), IN `@ModifiedDate` datetime, IN `@ModifiedBy` varchar(100), IN `@Code` int, IN `@Role` int)
BEGIN
  INSERT INTO employee (EmployeeID, EmployeeCode, EmployeeName, UserName, Password, AccountType, DateOfBirth, Gender, Email, PhoneNumber, Address, CompanyID, DepartmentID, PositionID, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, Code, Role)
    VALUES (`@EmployeeID`, `@EmployeeCode`, `@EmployeeName`, `@UserName`, `@Password`, `@AccountType`, `@DateOfBirth`, `@Gender`, `@Email`, `@PhoneNumber`, `@Address`, `@CompanyID`, `@DepartmentID`, `@PositionID`, `@CreatedDate`, `@CreatedBy`, `@ModifiedDate`, `@ModifiedBy`, `@Code`, `@Role`);
END
$$

--
-- Create procedure `Proc_GetUserByEmail_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetUserByEmail_Employee (IN `@Email` varchar(100))
COMMENT 'Lấy tên user'
BEGIN
  SELECT
    *
  FROM employee e
  WHERE e.Email = `@Email`;
END
$$

--
-- Create procedure `Proc_GetByUserPass_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetByUserPass_Employee (IN `@UserName` varchar(128), IN `@Email` varchar(100), IN `@Password` varchar(128))
COMMENT 'Kiểm tra đăng nhập'
BEGIN
  SELECT
    COUNT(*) AS Record
  FROM employee e
  WHERE (e.UserName = `@UserName`
  AND e.Password = `@Password`)
  OR (e.Email = `@Email`
  AND e.Password = `@Password`);
END
$$

--
-- Create procedure `Proc_GetAll_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetAll_Employee ()
COMMENT 'Lấy tất cả người dùng'
BEGIN
  SELECT
    *
  FROM employee e;
END
$$

DELIMITER ;

--
-- Create table `databaseinfo`
--
CREATE TABLE databaseinfo (
  DatabaseID char(36) NOT NULL DEFAULT '',
  DatabaseCode varchar(128) NOT NULL DEFAULT '',
  DatabaseName varchar(128) NOT NULL DEFAULT '',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (DatabaseID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng thông tin databse';

--
-- Create index `DatabaseCode` on table `databaseinfo`
--
ALTER TABLE databaseinfo
ADD UNIQUE INDEX DatabaseCode (DatabaseCode);

--
-- Create index `DatabaseName` on table `databaseinfo`
--
ALTER TABLE databaseinfo
ADD UNIQUE INDEX DatabaseName (DatabaseName);

DELIMITER $$

--
-- Create procedure `Proc_GetOne_Employee`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetOne_Employee (IN `@EmployeeID` char(36), IN `@UserName` varchar(128), IN `@Email` varchar(100))
BEGIN
  SELECT
    e.EmployeeID,
    e.EmployeeCode,
    e.EmployeeName,
    e.UserName,
    e.Password,
    e.AccountType,
    e.DateOfBirth,
    e.Gender,
    e.Email,
    e.PhoneNumber,
    e.Address,
    e.CompanyID,
    e.DepartmentID,
    e.PositionID,
    e.CreatedDate,
    e.CreatedBy,
    e.ModifiedDate,
    e.ModifiedBy,
    e.Code
  FROM employee e
  WHERE e.EmployeeID = `@EmployeeID`
  OR e.UserName = `@UserName`
  OR e.Email = `@Email`;
END
$$

DELIMITER ;

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('00382c7c-53a2-4932-a823-e6eb447a00a1', 'test2', 'test2', 'test2', '123qwe', 1, NULL, 1, 'dsf@gmail.com', 'dsfsdf', NULL, NULL, NULL, NULL, '2023-02-25 16:50:07', NULL, '2023-02-25 16:50:22', NULL, 0, 0),
('11db07ea-3a3f-169b-3c80-3a2297d01534', '2YU3', 'Allen1984', 'Mares2020', '123qwe', 0, '1963-10-11', 0, 'MinervaSeay@nowhere.com', '(384) 573-9515', '3574 East Burwood Hwy, 2nd Floor, Richmond, VA, 58220', 'be0ff46d-b4d7-11ed-8178-40167e258f11', 'be0ff4a4-b4d7-11ed-8178-40167e258f11', 'be0ff4ab-b4d7-11ed-8178-40167e258f11', '1999-01-03 20:41:10', 'Romeo Anderson', '1970-01-01 00:02:56', 'Lala Bachman', -854497783, 0),
('122a77f9-5685-12de-4080-3a2297d01534', '56VH', 'Stella2028', 'Abel47', '123qwe', 1, '1993-02-23', 2, 'MorrisEwing36@example.com', '(485) 122-7206', '79 SW Highland Loop, Jefferson City, MO, 19050', 'be0ffcf7-b4d7-11ed-8178-40167e258f11', 'be0ffd01-b4d7-11ed-8178-40167e258f11', 'be0ffd05-b4d7-11ed-8178-40167e258f11', '2010-08-10 11:10:42', 'Bernardo Adams', '1980-09-09 19:01:14', 'Beth Pacheco', -1624734023, 0),
('128c9c31-1636-6547-e269-4afe230d73a5', '02', 'Blanchard694', 'Flowers31', '123qwe', 0, '1964-11-17', 1, 'Shayna_Ahmed716@example.com', '(912) 155-9784', '3446 Hazelwood Way, Fisher Bldg, Olympia, WA, 70044', 'be0ffe47-b4d7-11ed-8178-40167e258f11', 'be0ffe4d-b4d7-11ed-8178-40167e258f11', 'be0ffe51-b4d7-11ed-8178-40167e258f11', '1970-01-01 01:12:19', 'Otis Calkins', '2013-02-20 21:17:29', 'Nikia Almond', -433, 0),
('13145f26-13f8-7f78-3e80-3a2297d01534', 'KT', 'Boris985', 'Calabrese1968', '123qwe', 1, '1954-10-19', 2, 'Tamera_Lemieux2@nowhere.com', '(348) 653-5855', '62 Edgewood Lane, Standard Bldg, Salem, OR, 28000', 'be0fff1c-b4d7-11ed-8178-40167e258f11', 'be0fff21-b4d7-11ed-8178-40167e258f11', 'be0fff25-b4d7-11ed-8178-40167e258f11', '2006-10-06 17:34:14', 'Rolande Price', '1988-02-20 23:08:58', 'Barry Allred', -1112741674, 0),
('131cd73b-3657-43f5-201e-21c6d80fbd76', 'N', 'Alarcon257', 'Merlene2002', '123qwe', 1, '1955-09-14', 0, 'JoaquinWilbanks@example.com', '(104) 855-4937', '273 NE Ashwood Loop, Atlanta, Georgia, 36856', 'be0fffeb-b4d7-11ed-8178-40167e258f11', 'be0ffff1-b4d7-11ed-8178-40167e258f11', 'be0ffff5-b4d7-11ed-8178-40167e258f11', '1973-06-09 16:57:48', 'Abe Tibbs', '1996-05-02 14:57:41', 'Luanne Jenkins', -1017700704, 0),
('153ab8dd-24df-3392-e569-4afe230d73a5', '9W63', 'Glover2002', 'Rochel1988', '123qwe', 1, '1977-09-22', NULL, 'Abigail_Gee@example.com', '(219) 107-9493', '665 Hidden Sharp Hill Cir, Appartment 827, Little Rock, Arkansas, 11194', 'be1000b0-b4d7-11ed-8178-40167e258f11', 'be1000b5-b4d7-11ed-8178-40167e258f11', 'be1000f6-b4d7-11ed-8178-40167e258f11', '2002-07-07 11:11:36', 'August Solano', NULL, NULL, -1888229580, 0),
('15b74345-3676-3005-feb4-c8af08a50cbf', 'B5', 'Lipscomb1963', 'Stuart2013', '123qwe', 0, '1960-03-15', 0, 'Marx@example.com', '(878) 677-6890', '1691 E Mount Loop, Fisher Bldg, Annapolis, Maryland, 61574', 'be1001d7-b4d7-11ed-8178-40167e258f11', 'be1001dd-b4d7-11ed-8178-40167e258f11', 'be1001e1-b4d7-11ed-8178-40167e258f11', '1999-05-28 11:45:07', 'Abigail Barney', '1987-03-30 11:33:42', 'Doug Adams', -336663742, 0),
('16901daa-2657-688d-274a-aea48a10ed18', 'CM6Q6', 'Quezada2021', 'Evangeline1952', '123qwe', 0, '1974-01-14', 2, 'Richie_Rand2@example.com', '(699) 939-1996', '631 West Brentwood Rd, Guardian Bldg, Augusta, ME, 97906', 'be100292-b4d7-11ed-8178-40167e258f11', 'be100298-b4d7-11ed-8178-40167e258f11', 'be10029c-b4d7-11ed-8178-40167e258f11', '1970-01-01 02:08:04', 'Barb Egan', '2017-06-27 10:02:20', 'Vickie Schultz', -768, 0),
('16fc94ab-327e-4d3a-3995-2c566fa88632', '5MQNA6O3W', 'Abram1', 'Connor2003', '123qwe', 0, '1968-07-28', 0, 'Mary.N_Kunkel572@example.com', '(273) 600-9445', '2413 Rockwood Dr, Nashville, Tennessee, 79428', 'be100362-b4d7-11ed-8178-40167e258f11', 'be100368-b4d7-11ed-8178-40167e258f11', 'be10036c-b4d7-11ed-8178-40167e258f11', '1989-04-05 03:55:31', 'Allan Canales', '1994-10-07 18:59:53', 'Scotty Kinney', -1733332493, 0),
('174b8763-2707-7cb1-3c71-153b37881afe', 'H4', 'Angel1992', 'Aleida749', '123qwe', 0, '1966-03-25', 2, 'Gee@nowhere.com', '(765) 713-9006', '1180 Parkwood Way, Salt Lake City, UT, 09708', 'be100419-b4d7-11ed-8178-40167e258f11', 'be10041e-b4d7-11ed-8178-40167e258f11', 'be100422-b4d7-11ed-8178-40167e258f11', '1981-08-10 13:37:49', 'Wesley Ramirez', '1971-10-02 21:41:17', 'Waltraud Lerma', -43612769, 0),
('17550e17-585d-701d-fdb4-c8af08a50cbf', '41', 'Rogelio2020', 'Elden2021', '123qwe', 1, '1953-01-01', 0, 'Cori_Darden@nowhere.com', '(155) 952-4000', '2898 White Mount Ln, Salt Lake City, Utah, 39971', 'be1004d0-b4d7-11ed-8178-40167e258f11', 'be1004d6-b4d7-11ed-8178-40167e258f11', 'be1004da-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:01', 'Tod Abbott', '2000-08-13 17:27:22', 'Lady Frey', 1, 0),
('176a9101-657e-3593-231e-21c6d80fbd76', 'C2X5', 'Akiko1964', 'Christy2014', '123qwe', 0, '1960-12-14', 1, 'FerdinandVanhorn@example.com', '(962) 016-0862', '66 Mount Hwy, 257 Towers Building, Santa Fe, NM, 33846', 'be10059d-b4d7-11ed-8178-40167e258f11', 'be1005a3-b4d7-11ed-8178-40167e258f11', 'be1005a7-b4d7-11ed-8178-40167e258f11', '1976-09-05 12:52:20', 'Kent Adame', '1981-02-02 19:24:51', 'Christene Stiles', -1104060368, 0),
('180dd722-49a7-2b93-fab4-c8af08a50cbf', '69', 'Barnhill2007', 'Lucas2021', '123qwe', 0, '1991-12-28', 1, 'Spann93@example.com', '(229) 446-3852', '1447 Prospect Hill Parkway, Annapolis, MD, 75495', 'be10065d-b4d7-11ed-8178-40167e258f11', 'be100662-b4d7-11ed-8178-40167e258f11', 'be100666-b4d7-11ed-8178-40167e258f11', '1999-03-24 06:48:41', 'Neal Bergman', '1970-01-01 00:00:07', 'Adalberto Thurston', -1109604616, 0),
('188263d8-1426-370e-3869-9f77bda75690', 'H', 'Dan4', 'Lindsay1', '123qwe', 1, '1973-05-04', 1, 'Armstrong5@example.com', '(594) 490-9628', '3683 Old Chapel Hill Ct, Appartment 280, Phoenix, AZ, 72450', 'be10072b-b4d7-11ed-8178-40167e258f11', 'be100731-b4d7-11ed-8178-40167e258f11', 'be100735-b4d7-11ed-8178-40167e258f11', '1982-09-06 21:26:24', 'Percy Valdes', '2002-03-06 12:54:46', 'Alana Means', -64006912, 0),
('1aa330a8-4e48-7daf-214a-aea48a10ed18', 'K2YN824GH1', 'Floria291', 'Heriberto97', '123qwe', 1, '1955-06-07', 0, 'LeilaBrubaker@example.com', '(553) 638-6830', '807 Front Road, Atlanta, Georgia, 07902', 'be1007e8-b4d7-11ed-8178-40167e258f11', 'be1007ed-b4d7-11ed-8178-40167e258f11', 'be1007f1-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:14:48', 'Kristle Dickens', '1981-04-19 02:36:34', 'Venice Steffen', -8, 0),
('1cd29b36-735e-4507-4395-2c566fa88632', '97', 'Amparo2002', 'Haywood1976', '123qwe', 0, '1996-05-29', 0, 'MarcelKimble521@example.com', '(721) 273-2988', '77 Hidden Prospect Hill Court, Providence, RI, 47634', 'be1008fd-b4d7-11ed-8178-40167e258f11', 'be100903-b4d7-11ed-8178-40167e258f11', 'be100907-b4d7-11ed-8178-40167e258f11', '2000-04-10 02:50:23', 'Olen Frey', '1998-08-15 01:14:36', 'Abel Collier', -1600601310, 0),
('1eb42cb0-2796-7c6b-4071-153b37881afe', 'VURH1XHWG', 'Elbert1966', 'Rodrick952', '123qwe', 0, '1976-01-10', 1, 'AnalisaThomas1@nowhere.com', '(447) 684-3013', '989 Glenwood Parkway, Atlanta, GA, 39339', 'be1009cd-b4d7-11ed-8178-40167e258f11', 'be1009d3-b4d7-11ed-8178-40167e258f11', 'be1009d7-b4d7-11ed-8178-40167e258f11', '2014-09-26 21:37:34', 'Gabriela Harmon', '1970-01-01 00:00:08', 'Gale Heffner', -1465693607, 0),
('1ef50b1c-1203-7f02-3a80-3a2297d01534', '3MN2CHLB1', 'Shea3', 'Santo492', '123qwe', 0, '1953-01-05', 1, 'Adan_Stafford@nowhere.com', '(768) 693-9345', '762 Old Hunting Hill Cir, 257 Towers Building, Lincoln, Nebraska, 78035', 'be100a8f-b4d7-11ed-8178-40167e258f11', 'be100a95-b4d7-11ed-8178-40167e258f11', 'be100a99-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:05', 'Avery Weeks', '1976-07-08 22:22:59', 'Verlie Burnside', 4, 0),
('1f818a24-3e97-339a-3b69-9f77bda75690', 'X32', 'Macklin267', 'Rowan495', '123qwe', 1, '1956-04-21', 0, 'nhbldqsc_kpfymwleux@example.com', '(604) 700-4191', '3559 Buttonwood Lane, Equitable Building, Cheyenne, WY, 18283', 'be100b63-b4d7-11ed-8178-40167e258f11', 'be100b69-b4d7-11ed-8178-40167e258f11', 'be100b6d-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:20:07', 'Buford Durden', '2022-09-19 12:15:03', 'Bertram Jefferson', -1206, 0),
('228b85f5-52b1-2110-e069-4afe230d73a5', 'M70', 'Maryellen126', 'Brownlee586', '123qwe', 0, '1982-06-24', 1, 'Flowers139@nowhere.com', '(403) 014-5022', '37 W Parkwood Parkway, 257 Towers Building, Dover, DE, 41095', 'be100c19-b4d7-11ed-8178-40167e258f11', 'be100c1f-b4d7-11ed-8178-40167e258f11', 'be100c23-b4d7-11ed-8178-40167e258f11', '1993-08-02 15:14:35', 'Alexandria Mendenhall', '2009-04-15 11:33:15', 'Kathie Bunn', -1760965754, 0),
('236283fa-1c9f-2733-221e-21c6d80fbd76', '2S', 'Lorri1978', 'Mena699', '123qwe', 1, '1970-01-29', 0, 'Abreu@example.com', '(405) 834-7270', '1456 Old Rockwood Highway, Comcast Building, Providence, RI, 95233', 'be100cd3-b4d7-11ed-8178-40167e258f11', 'be100cd8-b4d7-11ed-8178-40167e258f11', 'be100cdc-b4d7-11ed-8178-40167e258f11', '1991-03-06 15:45:43', 'Fermina Fields', '1970-01-01 00:01:36', 'Maddie Abraham', -889235045, 0),
('23d3e425-72b1-1755-254a-aea48a10ed18', 'A408', 'Landon77', 'Marya2', '123qwe', 1, '1962-05-11', 2, 'Acevedo@example.com', '(930) 466-4662', '2455 New Sharp Hill Ln, Albany, New York, 19886', 'be100d87-b4d7-11ed-8178-40167e258f11', 'be100d8c-b4d7-11ed-8178-40167e258f11', 'be100d90-b4d7-11ed-8178-40167e258f11', '2023-01-11 17:58:32', 'Isaura Hale', '1970-01-01 00:30:52', 'Adam Rigby', -2056366711, 0),
('2510011f-7734-4a66-3c69-9f77bda75690', '1', 'Poindexter715', 'Medrano19', '123qwe', 0, NULL, 0, 'MyrtieHeller@nowhere.com', NULL, NULL, 'be100e46-b4d7-11ed-8178-40167e258f11', 'be100e4c-b4d7-11ed-8178-40167e258f11', 'be100e50-b4d7-11ed-8178-40167e258f11', NULL, NULL, '2013-06-17 20:24:54', 'Emogene Stanton', NULL, 0),
('25d65c3f-4a6c-3a01-3c95-2c566fa88632', 'JM2Y0', 'Roberge5', 'Isidra124', '123qwe', 0, '1995-12-24', NULL, 'ArdellaPrince5@example.com', '(178) 531-2970', '75 Parkwood Loop, Diamond Building, Helena, Montana, 15708', 'be100efe-b4d7-11ed-8178-40167e258f11', 'be100f03-b4d7-11ed-8178-40167e258f11', 'be100f07-b4d7-11ed-8178-40167e258f11', '1971-06-24 20:59:45', 'Cliff Merrick', NULL, NULL, -1200721553, 0),
('26e66448-44a8-39c1-e669-4afe230d73a5', 'P', 'Birch1976', 'Alley2021', '123qwe', 0, '1953-12-30', 1, 'LaritaFalk4@example.com', '(409) 284-6799', '50 Rock Hill Hwy, Equitable Building, Concord, NH, 58041', 'be100fcb-b4d7-11ed-8178-40167e258f11', 'be100fd1-b4d7-11ed-8178-40167e258f11', 'be100fd5-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:06:04', 'Rupert Meyers', '2018-11-18 17:14:04', 'Alexa Alvarado', -36, 0),
('271a41be-5739-6088-3795-2c566fa88632', '1JC7168', 'Annamaria2005', 'Angila1963', '123qwe', 0, '1974-12-28', 1, 'MargaritoAnthony@example.com', '(812) 252-0427', '661 Riverside Hwy, APT 779, Jackson, MS, 67444', 'be10107f-b4d7-11ed-8178-40167e258f11', 'be101084-b4d7-11ed-8178-40167e258f11', 'be101088-b4d7-11ed-8178-40167e258f11', '1991-05-21 20:30:40', 'Rueben Sell', '1975-04-04 12:02:38', 'Candice Houser', -1099027689, 0),
('285bb738-292a-40ac-e469-4afe230d73a5', '6C', 'Jerold185', 'Scot2005', '123qwe', 1, '2000-05-04', 0, 'Mahaffey127@nowhere.com', '(973) 875-4972', '1207 New Chapel Hill Lane, 257 Towers Building, Honolulu, HI, 18064', 'be10116b-b4d7-11ed-8178-40167e258f11', 'be101171-b4d7-11ed-8178-40167e258f11', 'be101175-b4d7-11ed-8178-40167e258f11', '1986-11-25 18:28:04', 'Abdul Halsey', '1970-01-01 00:02:24', 'Martha Tobias', -868382218, 0),
('28aa154f-6d8f-745b-f8b4-c8af08a50cbf', '62', 'Marcelle62', 'Abbott1981', '123qwe', 1, '1953-01-02', 0, 'Anastacia.OPruitt48@example.com', '(442) 344-5339', '1039 Mountain Cir, Bismarck, ND, 33028', 'be101226-b4d7-11ed-8178-40167e258f11', 'be10122b-b4d7-11ed-8178-40167e258f11', 'be10122f-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:02', 'Aide Manley', '1997-01-25 14:53:11', 'Tanna Moreno', 18, 0),
('29318abd-6a6c-7a98-ffb4-c8af08a50cbf', 'Z', 'Adelaida649', 'Adan548', '123qwe', 0, NULL, 2, 'thpbl388@example.com', NULL, NULL, 'be1012df-b4d7-11ed-8178-40167e258f11', 'be1012e5-b4d7-11ed-8178-40167e258f11', 'be1012e8-b4d7-11ed-8178-40167e258f11', NULL, NULL, '2000-07-18 22:11:21', 'Margarett Adcock', NULL, 0),
('2997b570-182c-1e2e-2c26-978952f080e4', 'YU0I0X', 'Messina2015', 'Elenore125', '123qwe', 0, '1975-02-27', 1, 'Geraldo_Tompkins@example.com', '(706) 801-7851', '739 NE Hunting Hill Road, 1st Floor, Richmond, Virginia, 26457', 'be1013de-b4d7-11ed-8178-40167e258f11', 'be1013e4-b4d7-11ed-8178-40167e258f11', 'be1013e8-b4d7-11ed-8178-40167e258f11', '2014-12-28 15:29:50', 'Gilberto Wallis', '1970-01-01 00:00:04', 'Connie Abrams', -2114134956, 0),
('2a3cacd6-1a30-6760-3769-9f77bda75690', '515N', 'Katelin2027', 'Robb636', '123qwe', 1, '1955-09-17', 0, 'Cordero@example.com', '(826) 366-1014', '2060 Hunting Hill Lane, 1st FL, Boston, MA, 64980', 'be1014a0-b4d7-11ed-8178-40167e258f11', 'be1014a6-b4d7-11ed-8178-40167e258f11', 'be1014aa-b4d7-11ed-8178-40167e258f11', '2002-06-13 12:17:07', 'Almeta Bowling', '1985-06-26 01:47:08', 'Kourtney Flood', -5034261, 0),
('2a4dcb61-3cde-2171-2a26-978952f080e4', 'I305', 'Kellie7', 'Shantelle586', '123qwe', 0, '1954-06-16', 2, 'ahukz6794@example.com', '(360) 865-3659', '130 West Beachwood Ct, Lincoln, NE, 16780', 'be10155a-b4d7-11ed-8178-40167e258f11', 'be101560-b4d7-11ed-8178-40167e258f11', 'be101563-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:08:52', 'Jamika Mendez', '2002-07-27 06:26:45', 'Emilio Burnside', -5, 0),
('2af78bcb-2bab-51c2-57cb-b8d37b68af4d', '51', 'Acevedo683', 'Hendrix44', '123qwe', 1, '1962-12-27', 2, 'Barrett.JAnderson6@example.com', '(656) 528-3211', '33 Prospect Hill Parkway, Dover, Delaware, 55123', 'be101622-b4d7-11ed-8178-40167e258f11', 'be101628-b4d7-11ed-8178-40167e258f11', 'be10162b-b4d7-11ed-8178-40167e258f11', '2001-01-09 23:32:07', 'Herschel Abreu', '1970-01-01 01:21:14', 'Virginia Loera', -470245091, 0),
('2b5f15b9-17d9-57e8-1e4a-aea48a10ed18', '83RV', 'Avery1956', 'Abraham123', '123qwe', 0, '1964-09-11', 2, 'Jennings@example.com', '(133) 683-0582', '3162 1st Pkwy, Jackson, Mississippi, 84395', 'be1016d2-b4d7-11ed-8178-40167e258f11', 'be1016d7-b4d7-11ed-8178-40167e258f11', 'be1016db-b4d7-11ed-8178-40167e258f11', '1982-03-09 15:26:31', 'Edward Jarvis', '1994-05-26 01:30:59', 'Adolfo Parks', -43693409, 0),
('2bd742e7-2f5a-3eae-241e-21c6d80fbd76', 'T65', 'Buckley447', 'Seal153', '123qwe', 0, '1953-04-10', 0, 'Mccune@nowhere.com', '(122) 257-5628', '897 Rock Hill Drive, Montgomery, Alabama, 58083', 'be101787-b4d7-11ed-8178-40167e258f11', 'be10178d-b4d7-11ed-8178-40167e258f11', 'be101791-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:01:40', 'Andria Powell', '2021-08-15 00:58:24', 'Caterina Mills', 9901, 0),
('2cca9dd5-1228-294d-3e71-153b37881afe', '9YN', 'Marhta5', 'Delaine8', '123qwe', 1, '1953-02-23', 2, 'FelixD.Shoemaker@example.com', '(135) 721-2385', '1550 White Prospect Hill Hwy, Charleston, West Virginia, 82628', 'be10184e-b4d7-11ed-8178-40167e258f11', 'be101854-b4d7-11ed-8178-40167e258f11', 'be101857-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:54', 'Abdul Rainey', '1997-05-17 04:55:22', 'Duane Alaniz', 5342, 0),
('2cf45a23-4a27-72fb-3f95-2c566fa88632', 'Q599', 'Oconnor2026', 'Delphia378', '123qwe', 0, '1992-12-10', 1, 'Felton99@nowhere.com', '(310) 050-6594', '1988 Hidden Mountain Blvd, Columbus, OH, 63780', 'be101906-b4d7-11ed-8178-40167e258f11', 'be10190c-b4d7-11ed-8178-40167e258f11', 'be101910-b4d7-11ed-8178-40167e258f11', '1993-12-02 02:47:40', 'Sharolyn Brockman', '1970-01-01 00:01:06', 'Melynda Bigelow', -17786186, 0),
('3052c754-3516-667a-3980-3a2297d01534', 'QI94TW', 'Lyons2007', 'Angla5', '123qwe', 0, '1993-04-19', 2, 'GladisReeves33@example.com', '(977) 813-8110', '1435 1st Blvd, Atlanta, GA, 32143', 'be1019b3-b4d7-11ed-8178-40167e258f11', 'be1019b8-b4d7-11ed-8178-40167e258f11', 'be1019bc-b4d7-11ed-8178-40167e258f11', '1996-12-17 10:52:58', 'Porsha Minton', '2022-03-22 02:21:19', 'Buena Abreu', -41165870, 0),
('34bd2cef-5026-567c-3b71-153b37881afe', '7', 'Leigh6', 'Sauls1979', '123qwe', 0, '1953-01-09', 2, 'LealU19@nowhere.com', '(260) 313-6443', '3269 Rose Hill Hwy, Jefferson City, Missouri, 33825', 'be101a80-b4d7-11ed-8178-40167e258f11', 'be101a86-b4d7-11ed-8178-40167e258f11', 'be101a8a-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:09', 'Adelaida Bergman', '2015-11-15 12:47:45', 'Alaine Hickey', 8, 0),
('3679a94f-304b-6e8d-53cb-b8d37b68af4d', '0CQ2', 'Albertine968', 'Jeffries9', '123qwe', 0, '1953-01-02', 1, 'Alston679@example.com', '(487) 479-9336', '179 2nd Rd, Superior Bldg, Austin, TX, 72670', 'be101b32-b4d7-11ed-8178-40167e258f11', 'be101b38-b4d7-11ed-8178-40167e258f11', 'be101b3b-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:02', 'Travis Abney', '1996-11-22 00:40:27', 'Victor Tejeda', 1, 0),
('36c45179-1fc2-27b2-3b95-2c566fa88632', '5', 'Cora2009', 'Jerald1984', '123qwe', 0, '1954-06-09', 0, 'GertudePlace@nowhere.com', '(845) 678-6842', '3896 SW Glenwood Dr, Honolulu, HI, 51236', 'be101be9-b4d7-11ed-8178-40167e258f11', 'be101bef-b4d7-11ed-8178-40167e258f11', 'be101bf3-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:08:45', 'Augustus Abreu', '1983-04-10 21:34:12', 'Scarlett Dugger', -5, 0),
('3762edc1-6275-6d66-e769-4afe230d73a5', '35S3R', 'Meghan2022', 'Adrien137', '123qwe', 1, NULL, NULL, 'Abrams@example.com', NULL, NULL, 'be101c9c-b4d7-11ed-8178-40167e258f11', 'be101ca2-b4d7-11ed-8178-40167e258f11', 'be101ca6-b4d7-11ed-8178-40167e258f11', NULL, NULL, NULL, NULL, NULL, 0),
('38d0c8d3-7e6b-7ced-4095-2c566fa88632', '0Y2JGW', 'Alissa1999', 'Kamilah1964', '123qwe', 0, '1966-12-06', NULL, 'Vallejo427@example.com', '(488) 093-9430', '3996 Buttonwood Pkwy, Diamond Building, Denver, CO, 00355', 'be101d62-b4d7-11ed-8178-40167e258f11', 'be101d68-b4d7-11ed-8178-40167e258f11', 'be101d6b-b4d7-11ed-8178-40167e258f11', '2001-03-13 12:07:46', 'Chloe Villalobos', NULL, NULL, -823383457, 0),
('3a8da253-7acf-2c70-2e26-978952f080e4', 'P462', 'Retha1976', 'Card2', '123qwe', 0, NULL, NULL, 'Troy.Almanza@nowhere.com', NULL, NULL, 'be101e12-b4d7-11ed-8178-40167e258f11', 'be101e17-b4d7-11ed-8178-40167e258f11', 'be101e1b-b4d7-11ed-8178-40167e258f11', NULL, NULL, NULL, NULL, NULL, 0),
('3c39055f-64c2-11b9-f7b4-c8af08a50cbf', 'EZI41K3', 'Rufus845', 'Emery569', '123qwe', 0, '1955-02-02', 2, 'DominickGrier@nowhere.com', '(790) 495-8216', '767 Chapel Hill Ln, Keith Building, Providence, RI, 80951', 'be101f09-b4d7-11ed-8178-40167e258f11', 'be101f0f-b4d7-11ed-8178-40167e258f11', 'be101f13-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:12:43', 'Clemmie Grove', '1983-02-21 05:25:14', 'Tawna Abel', -76, 0),
('3c91bd67-6353-1edc-1f4a-aea48a10ed18', 'NH3VM9', 'Charlette2012', 'Selma2028', '123qwe', 0, '1993-09-23', 2, 'Adair77@example.com', '(768) 048-0640', '98 New Monument Blvd, Santa Fe, New Mexico, 23743', 'be101fc4-b4d7-11ed-8178-40167e258f11', 'be101fca-b4d7-11ed-8178-40167e258f11', 'be101fcd-b4d7-11ed-8178-40167e258f11', '1993-01-24 18:30:00', 'Vance Blaine', '2006-09-04 21:02:23', 'Bonita Draper', -526509683, 0),
('3cf1ead4-291e-575d-3b80-3a2297d01534', 'QW1R', 'Crysta621', 'Ela1958', '123qwe', 1, '1987-12-31', 0, 'Matney@example.com', '(857) 863-6779', '796 S Town Circle, Duke Energy Building, Cheyenne, Wyoming, 66607', 'be102088-b4d7-11ed-8178-40167e258f11', 'be10208e-b4d7-11ed-8178-40167e258f11', 'be102092-b4d7-11ed-8178-40167e258f11', '1972-08-09 18:36:53', 'Judson Oh', '2018-05-23 06:50:54', 'Addie Jacobsen', -1511615856, 0),
('3e1a01ba-4a49-2570-2d26-978952f080e4', 'WTH3997', 'Lombardo983', 'Andra2028', '123qwe', 0, '1955-09-16', 0, 'Dorian_K_Sweeney27@example.com', '(772) 255-9570', '2688 Hope Highway, STE 3, Austin, TX, 49476', 'be10213b-b4d7-11ed-8178-40167e258f11', 'be102140-b4d7-11ed-8178-40167e258f11', 'be102144-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:16:29', 'Whitney Sands', '1992-02-13 09:55:29', 'Ervin Rafferty', -9, 0),
('3e805329-4dde-7c42-3f80-3a2297d01534', 'V', 'Almeida1983', 'Calabrese1982', '123qwe', 1, '1995-07-22', 2, 'Titus1@nowhere.com', '(699) 953-3419', '605 W Parkwood Cir, Denver, Colorado, 17764', 'be1021f1-b4d7-11ed-8178-40167e258f11', 'be1021f6-b4d7-11ed-8178-40167e258f11', 'be1021fa-b4d7-11ed-8178-40167e258f11', '2013-11-01 16:34:16', 'Parthenia Pomeroy', '2006-08-02 00:53:45', 'Ryan Abbott', -1438103282, 0),
('3ef40874-7653-5c65-2726-978952f080e4', 'H6', 'Garret2012', 'German1978', '123qwe', 0, '1996-12-31', NULL, 'Crooks@nowhere.com', '(227) 049-9918', '440 Mountain Ave, Duke Energy Bldg, Indianapolis, IN, 03263', 'be1022a9-b4d7-11ed-8178-40167e258f11', 'be1022ae-b4d7-11ed-8178-40167e258f11', 'be1022b2-b4d7-11ed-8178-40167e258f11', '1998-08-01 00:28:29', 'Christian Gill', NULL, NULL, -1837413052, 0),
('406501b7-7932-293c-3e95-2c566fa88632', 'M0BP', 'Omar2027', 'Lincoln2011', '123qwe', 1, '1955-12-30', 2, 'Frazer@nowhere.com', '(100) 792-3782', '3489 Prospect Hill Court, Sacramento, California, 16264', 'be102359-b4d7-11ed-8178-40167e258f11', 'be10235e-b4d7-11ed-8178-40167e258f11', 'be102362-b4d7-11ed-8178-40167e258f11', '2022-05-05 22:36:25', 'Roland Clem', '1978-10-18 07:49:06', 'Sheba Paige', -1402010195, 0),
('42784277-1650-434a-251e-21c6d80fbd76', 'U5C', 'Ada1978', 'Vargas11', '123qwe', 1, NULL, NULL, 'JewellYbarra@nowhere.com', NULL, NULL, 'be10240b-b4d7-11ed-8178-40167e258f11', 'be102410-b4d7-11ed-8178-40167e258f11', 'be102414-b4d7-11ed-8178-40167e258f11', NULL, NULL, NULL, NULL, NULL, 0),
('42950a9c-2cfa-3933-4271-153b37881afe', '36666U', 'Shelby1970', 'Ashlyn161', '123qwe', 0, '1953-01-02', 2, 'Geneva.Gantt891@nowhere.com', '(890) 115-4668', '27 Hope Circle, Lincoln, Nebraska, 16154', 'be1024b6-b4d7-11ed-8178-40167e258f11', 'be1024bb-b4d7-11ed-8178-40167e258f11', 'be1024be-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:02', 'Jutta Wiseman', '1970-01-01 00:03:03', 'Theola Krieger', 1, 0),
('42e76f39-5529-3e7f-e369-4afe230d73a5', '72KS09', 'Louie1', 'Siobhan2025', '123qwe', 1, '1953-04-08', 1, 'ForteO@example.com', '(174) 976-3425', '2239 Meadowview Parkway, Calyon Building, Concord, NH, 38909', 'be102563-b4d7-11ed-8178-40167e258f11', 'be102568-b4d7-11ed-8178-40167e258f11', 'be10256c-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:01:38', 'Laurette Larose', '1979-04-01 01:14:25', 'Rene Kemper', 9719, 0),
('438598e2-2574-4fc8-2626-978952f080e4', '4SCUB3L1', 'Rebecca1983', 'Racheal2025', '123qwe', 1, '1953-01-01', 1, 'owpk8399@example.com', '(451) 929-8321', '2244 Deepwood Dr, Nipper Building, Carson City, NV, 23293', 'be10260c-b4d7-11ed-8178-40167e258f11', 'be102611-b4d7-11ed-8178-40167e258f11', 'be102615-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:01', 'Edgar Adler', '1973-08-24 05:15:28', 'Monroe Gatewood', 0, 0),
('43a6bdf5-1b6b-451b-3695-2c566fa88632', 'X1465AOEX9BT', 'Alaniz9', 'Craig2020', '123qwe', 0, '1958-03-15', 2, 'kkhx3854@example.com', '(868) 864-8718', '398 W Glenwood Court, Springfield, IL, 21937', 'be1026dd-b4d7-11ed-8178-40167e258f11', 'be1026e3-b4d7-11ed-8178-40167e258f11', 'be1026e6-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:31:40', 'Abram Patten', '2022-04-06 03:34:39', 'Trey Christopher', -189, 0),
('43c28052-24df-5238-2a4a-aea48a10ed18', '934', 'Emanuel2024', 'Sams1975', '123qwe', 1, '2000-09-13', 2, 'Cobb@nowhere.com', '(951) 745-7936', '1563 Ironwood Ln, Oklahoma City, Oklahoma, 21657', 'be102794-b4d7-11ed-8178-40167e258f11', 'be102799-b4d7-11ed-8178-40167e258f11', 'be10279d-b4d7-11ed-8178-40167e258f11', '2022-06-20 21:12:04', 'Reta Wilbanks', '2015-01-28 00:56:46', 'Cary Embry', -1952738844, 0),
('44eaf230-462a-493b-3d80-3a2297d01534', 'R', 'Carmelo1971', 'Cyrus1985', '123qwe', 0, NULL, 2, 'LucioDolan@example.com', NULL, NULL, 'be1028a0-b4d7-11ed-8178-40167e258f11', 'be1028a6-b4d7-11ed-8178-40167e258f11', 'be1028aa-b4d7-11ed-8178-40167e258f11', NULL, NULL, '1995-07-22 03:37:32', 'Tommye Allman', NULL, 0),
('44edba69-403e-3174-4171-153b37881afe', '1E860F', 'Adamson1980', 'Casimira519', '123qwe', 1, '1970-09-30', 1, 'vzng8215@nowhere.com', '(797) 895-0572', '2302 SW Hope Ct, Nipper Building, Boise, ID, 61850', 'be102958-b4d7-11ed-8178-40167e258f11', 'be10295e-b4d7-11ed-8178-40167e258f11', 'be102962-b4d7-11ed-8178-40167e258f11', '1984-06-24 09:34:11', 'Vincenzo Homan', '1970-01-01 00:05:18', 'Delaine Escalante', -1060798109, 0),
('4511c5e9-17d7-743e-2b4a-aea48a10ed18', '3W', 'Shanta2025', 'Avelina1974', '123qwe', 1, '1975-02-06', 2, 'Rhett.Streeter28@nowhere.com', '(335) 439-3691', '32 NW Quailwood Street, Nipper Bldg, Juneau, Alaska, 55187', 'be102a55-b4d7-11ed-8178-40167e258f11', 'be102a5b-b4d7-11ed-8178-40167e258f11', 'be102a5f-b4d7-11ed-8178-40167e258f11', '1971-10-28 21:24:33', 'Tamiko Lance', '1970-01-01 00:00:04', 'Abbie Kitchens', -1119629883, 0),
('4569f996-12b0-64d5-54cb-b8d37b68af4d', 'E1872', 'Norberto665', 'Benito1971', '123qwe', 0, '1988-11-22', 1, 'Muriel_QMilliken5@example.com', '(875) 375-2382', '3046 Rock Hill Pkwy, Juneau, AK, 36054', 'be102b17-b4d7-11ed-8178-40167e258f11', 'be102b1c-b4d7-11ed-8178-40167e258f11', 'be102b20-b4d7-11ed-8178-40167e258f11', '2012-08-13 00:57:56', 'Alease Perales', '1994-02-07 09:04:56', 'Adalberto Bishop', -92868201, 0),
('48d04691-671b-2f98-de69-4afe230d73a5', 'S7', 'Adler762', 'Abraham1995', '123qwe', 0, '1995-10-27', 1, 'PhilRichey8@example.com', '(447) 838-0332', '3105 Ski Hill Ln, Diamond Building, Santa Fe, NM, 87770', 'be102bc3-b4d7-11ed-8178-40167e258f11', 'be102bc8-b4d7-11ed-8178-40167e258f11', 'be102bcc-b4d7-11ed-8178-40167e258f11', '1998-06-12 18:20:25', 'Gregg Fulmer', '1982-03-17 07:46:33', 'Clair Montes', -253056049, 0),
('48ecd789-755b-3d53-3f71-153b37881afe', 'C2X0', 'Perry166', 'Alford2002', '123qwe', 0, '1953-01-07', 1, 'Blank783@example.com', '(861) 866-2316', '33 Meadowview Way, Oklahoma City, Oklahoma, 49895', 'be102c72-b4d7-11ed-8178-40167e258f11', 'be102c78-b4d7-11ed-8178-40167e258f11', 'be102c7c-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:07', 'Adaline Shah', '1984-06-30 06:37:04', 'Velva Harder', 62, 0),
('492c33d2-2e7e-39f3-2926-978952f080e4', '93JM7ERD2', 'Julio1986', 'Vernon1963', '123qwe', 0, '1972-10-28', 0, 'Luigi.Duvall448@example.com', '(649) 790-3129', '553 Prospect Hill Lane, Duke Energy Bldg, Baton Rouge, Louisiana, 81074', 'be102d1c-b4d7-11ed-8178-40167e258f11', 'be102d22-b4d7-11ed-8178-40167e258f11', 'be102d25-b4d7-11ed-8178-40167e258f11', '2011-04-18 10:25:58', 'Rory Burchfield', '1970-12-28 14:50:36', 'Monroe Hamblin', -387252890, 0),
('4abe5367-730a-5742-59cb-b8d37b68af4d', '2V2', 'Daron582', 'Bowlin1986', '123qwe', 0, '1978-12-20', 1, 'IsmaelParra815@nowhere.com', '(189) 569-6760', '992 S Brentwood Avenue, Topeka, KS, 21205', 'be102dd2-b4d7-11ed-8178-40167e258f11', 'be102dd7-b4d7-11ed-8178-40167e258f11', 'be102ddb-b4d7-11ed-8178-40167e258f11', '2019-10-23 10:00:16', 'Austin Keaton', '1970-01-01 00:02:27', 'Asuncion Abel', -285595550, 0),
('4b7e1819-5124-575e-4471-153b37881afe', 'JJ', 'Candance296', 'Alvin8', '123qwe', 1, NULL, 0, 'DanialMcmillan@nowhere.com', NULL, NULL, 'be102f53-b4d7-11ed-8178-40167e258f11', 'be102f5b-b4d7-11ed-8178-40167e258f11', 'be102f5f-b4d7-11ed-8178-40167e258f11', NULL, NULL, '2020-11-13 05:11:36', 'Jordon Strong', NULL, 0),
('4c14b14c-7023-7881-2f26-978952f080e4', '3I2', 'Aida29', 'Abney46', '123qwe', 1, NULL, NULL, 'TyronKnight@example.com', NULL, NULL, 'be10301e-b4d7-11ed-8178-40167e258f11', 'be103023-b4d7-11ed-8178-40167e258f11', 'be103027-b4d7-11ed-8178-40167e258f11', NULL, NULL, NULL, NULL, NULL, 0),
('4cad8606-32c9-3513-fbb4-c8af08a50cbf', 'U', 'Todd1981', 'Benjamin482', '123qwe', 1, '2002-10-08', 0, 'Shemika_Marin955@example.com', '(963) 470-5904', '30 Ironwood Blvd, Denver, Colorado, 50581', 'be1030ca-b4d7-11ed-8178-40167e258f11', 'be1030cf-b4d7-11ed-8178-40167e258f11', 'be1030d3-b4d7-11ed-8178-40167e258f11', '1986-08-04 08:55:11', 'Bryon Vigil', '2013-08-22 19:29:41', 'Ron Abney', -368838617, 0),
('4efb4721-715b-2d1c-264a-aea48a10ed18', 'B7VJ6H', 'Tate1988', 'Syble2000', '123qwe', 1, '1981-01-17', 1, 'rxypas30@nowhere.com', '(603) 182-0120', '966 Hidden Hunting Hill Pkwy, Raleigh, North Carolina, 03843', 'be103193-b4d7-11ed-8178-40167e258f11', 'be103198-b4d7-11ed-8178-40167e258f11', 'be10319c-b4d7-11ed-8178-40167e258f11', '1975-01-18 20:42:19', 'Arnold Abrams', '1970-01-01 00:00:07', 'Francis Mcintyre', -846571331, 0),
('5330491b-2e0d-76e5-294a-aea48a10ed18', 'YH', 'Domingo868', 'Kayce33', '123qwe', 0, '1982-07-09', 1, 'xujb12@example.com', '(771) 958-1706', '2178 Rock Hill Road, Phoenix, Arizona, 50286', 'be10323f-b4d7-11ed-8178-40167e258f11', 'be103245-b4d7-11ed-8178-40167e258f11', 'be103249-b4d7-11ed-8178-40167e258f11', '1999-08-13 15:53:36', 'Minerva Clifton', '1970-01-01 00:01:00', 'Joycelyn Addison', -513533647, 0),
('534b8747-70b5-36a6-58cb-b8d37b68af4d', 'V2M', 'Adelaida2019', 'Nick933', '123qwe', 0, '2002-11-08', 0, 'Maud_KDollar4@nowhere.com', '(390) 393-2410', '701 Church Loop, Harrisburg, PA, 00384', 'be1032f5-b4d7-11ed-8178-40167e258f11', 'be1032fa-b4d7-11ed-8178-40167e258f11', 'be1032fe-b4d7-11ed-8178-40167e258f11', '2017-07-06 03:15:06', 'Shaunda Escalante', '2003-04-02 21:36:39', 'Ying Connell', -2055638394, 0),
('536f0d7b-6fd5-2bb9-52cb-b8d37b68af4d', 'K8B5V0D82', 'Edward1982', 'Tyron1995', '123qwe', 1, '2000-08-31', 2, 'PeggieScott@example.com', '(914) 159-1651', '284 E Stonewood Blvd, Hartford, CT, 18421', 'be1033a9-b4d7-11ed-8178-40167e258f11', 'be1033af-b4d7-11ed-8178-40167e258f11', 'be1033b2-b4d7-11ed-8178-40167e258f11', '2000-11-02 04:22:26', 'Leonora Houser', '1972-07-27 16:07:36', 'Minta Caruso', -1896361655, 0),
('59c8e347-352c-11cc-4195-2c566fa88632', 'W', 'Coralee366', 'Jose1989', '123qwe', 1, '1964-06-27', 1, 'doku6880@example.com', '(444) 407-6148', '357 New Stonewood Hwy, Penobscot Bldg, Juneau, AK, 75902', 'be103456-b4d7-11ed-8178-40167e258f11', 'be10345b-b4d7-11ed-8178-40167e258f11', 'be10345f-b4d7-11ed-8178-40167e258f11', '1992-04-10 01:12:29', 'Rueben Viera', '1976-03-12 03:18:09', 'Delaine Crump', -515662517, 0),
('59d2ec76-7794-6092-284a-aea48a10ed18', '918W', 'Duvall1953', 'Jasmin2006', '123qwe', 1, '1954-07-25', 2, 'Stewart_Ashcraft9@example.com', '(778) 175-1634', '161 Social Parkway, Atlanta, GA, 66872', 'be103b96-b4d7-11ed-8178-40167e258f11', 'be103ba2-b4d7-11ed-8178-40167e258f11', 'be103ba6-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:09:31', 'Adam Mccarty', '1999-10-13 08:42:14', 'Josiah Cuellar', -57, 0),
('5c9053fa-24e2-218e-e169-4afe230d73a5', 'B1', 'Louise368', 'Adan2001', '123qwe', 0, '1985-01-09', 0, 'BernardoBarkley1@example.com', '(995) 647-4714', '1726 E Stonewood Ct, Buhl Bldg, Saint Paul, Minnesota, 53056', 'be10611d-b4d7-11ed-8178-40167e258f11', 'be10618a-b4d7-11ed-8178-40167e258f11', 'be10618e-b4d7-11ed-8178-40167e258f11', '2018-08-26 21:05:18', 'Mistie Musgrove', '1987-10-05 22:05:34', 'Andres Soria', -128493620, 0),
('5cf37f24-5c9d-49a9-4371-153b37881afe', 'MH', 'Dion9', 'Almeida271', '123qwe', 1, '1979-02-23', 1, 'JoyceP@example.com', '(989) 372-3071', '2755 East Highland Cir, Trenton, NJ, 17275', 'be10633c-b4d7-11ed-8178-40167e258f11', 'be106343-b4d7-11ed-8178-40167e258f11', 'be106347-b4d7-11ed-8178-40167e258f11', '2004-08-05 10:16:02', 'Adelina Browne', '1970-01-01 00:00:06', 'Teri Almanza', -1612204747, 0),
('5e95cda4-3f52-314f-f9b4-c8af08a50cbf', '6L', 'Valdes5', 'Runyon634', '123qwe', 1, '1998-02-01', 0, 'DrewTravis253@example.com', '(598) 443-5163', '3728 Woodcock Street, Phoenix, Arizona, 60862', 'be106406-b4d7-11ed-8178-40167e258f11', 'be10640b-b4d7-11ed-8178-40167e258f11', 'be10640f-b4d7-11ed-8178-40167e258f11', '2005-01-12 00:04:44', 'Seth Ojeda', '1970-01-01 00:03:47', 'Winford Milner', -215215921, 0),
('5fc77644-30f7-78aa-3d69-9f77bda75690', 'P6509', 'Banks1952', 'Ladd76', '123qwe', 1, '2001-02-13', 0, 'Triplett38@example.com', '(294) 880-8987', '72 South Hunting Hill Loop, Harrisburg, Pennsylvania, 93283', 'be1064dc-b4d7-11ed-8178-40167e258f11', 'be1064e1-b4d7-11ed-8178-40167e258f11', 'be1064e4-b4d7-11ed-8178-40167e258f11', '2010-11-03 22:31:13', 'Mike Burgos', '1984-04-26 21:12:48', 'Carlton Christian', -964725025, 0),
('63605f9a-664d-1c51-fcb4-c8af08a50cbf', '5H99', 'Marcos79', 'Badger219', '123qwe', 0, '1953-01-01', 2, 'khbzvt398@example.com', '(170) 817-8391', '298 Woodhurst Cir, APT 68, Phoenix, AZ, 00121', 'be106595-b4d7-11ed-8178-40167e258f11', 'be10659a-b4d7-11ed-8178-40167e258f11', 'be10659e-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:01', 'Adela Haggard', '1970-01-01 00:01:25', 'Benny Abbott', 2, 0),
('64a59a25-2488-54b0-f6b4-c8af08a50cbf', '7782C8B', 'Acker7', 'Norris377', '123qwe', 0, '1994-12-14', 0, 'Adam.Acker24@example.com', '(564) 517-5025', '2076 Ski Hill Highway, Olympia, WA, 90087', 'be10668d-b4d7-11ed-8178-40167e258f11', 'be106693-b4d7-11ed-8178-40167e258f11', 'be106697-b4d7-11ed-8178-40167e258f11', '1990-10-14 17:44:01', 'Scot Acker', '1970-01-01 02:13:43', 'Norris Calderon', -1152206898, 0),
('64a92470-6127-1432-211e-21c6d80fbd76', '13N3J7J', 'Adan97', 'Abney1989', '123qwe', 1, NULL, NULL, 'Violeta_Tribble832@example.com', NULL, NULL, 'be106748-b4d7-11ed-8178-40167e258f11', 'be10674d-b4d7-11ed-8178-40167e258f11', 'be106751-b4d7-11ed-8178-40167e258f11', NULL, NULL, NULL, NULL, NULL, 0),
('6558b3ce-3021-5467-4295-2c566fa88632', 'CHBF', 'Joe2020', 'Elliot2003', '123qwe', 1, '1955-03-21', 1, 'DeshawnIsbell@nowhere.com', '(435) 983-1093', '186 Beachwood Ct, 2nd Floor, Boise, Idaho, 88016', 'be106809-b4d7-11ed-8178-40167e258f11', 'be10680f-b4d7-11ed-8178-40167e258f11', 'be106813-b4d7-11ed-8178-40167e258f11', '1998-07-08 23:10:05', 'Alexis Fagan', '1976-06-29 14:25:38', 'Austin Aiken', -545768229, 0),
('67408602-4805-48a7-224a-aea48a10ed18', 'T', 'Dalia2024', 'Thao237', '123qwe', 0, '1972-03-21', 2, 'Villalobos7@example.com', '(243) 459-7372', '1852 Edgewood St, Trenton, NJ, 83770', 'be1068bd-b4d7-11ed-8178-40167e258f11', 'be1068c2-b4d7-11ed-8178-40167e258f11', 'be1068c6-b4d7-11ed-8178-40167e258f11', '2005-02-16 13:58:05', 'Jamie Aguiar', '1978-12-25 22:48:31', 'Josef Abrams', -402327845, 0),
('674934cc-42cf-20cf-1d4a-aea48a10ed18', '8', 'Rodolfo36', 'Roxane2028', '123qwe', 1, '1953-01-07', 2, 'byiswceo_myqdc@example.com', '(684) 186-0087', '3736 White Hunting Hill Cir, Augusta, Maine, 17410', 'be10696c-b4d7-11ed-8178-40167e258f11', 'be106971-b4d7-11ed-8178-40167e258f11', 'be106975-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:07', 'Albert Mclean', '1995-12-29 04:39:19', 'Aileen Pitts', 69, 0),
('69b684a9-3962-48e7-56cb-b8d37b68af4d', '6743', 'Hooker2016', 'Fred2007', '123qwe', 0, '1969-07-09', NULL, 'Kareem.Ratliff@example.com', '(864) 550-3567', '959 Ironwood Blvd, Guardian Building, Richmond, VA, 15397', 'be106a24-b4d7-11ed-8178-40167e258f11', 'be106a29-b4d7-11ed-8178-40167e258f11', 'be106a2d-b4d7-11ed-8178-40167e258f11', '1973-11-23 07:33:39', 'Melvin Sommers', NULL, NULL, -754329531, 0),
('6acf37bb-5f8e-320e-3969-9f77bda75690', 'R76XG', 'Kati61', 'Moira1983', '123qwe', 1, '1991-11-20', 0, 'Caleb.Lincoln2@example.com', '(821) 308-8608', '2481 NW Riddle Hill Ct, Buhl Building, Frankfort, KY, 70763', 'be106ae3-b4d7-11ed-8178-40167e258f11', 'be106ae8-b4d7-11ed-8178-40167e258f11', 'be106aec-b4d7-11ed-8178-40167e258f11', '2002-06-12 02:55:32', 'Kyung Andrew', '1975-02-24 02:58:44', 'Florentino Cranford', -1584135024, 0),
('6d3b9bea-50e2-3fe2-3d95-2c566fa88632', 'PM4L53F0', 'Chu2011', 'Alfredia5', '123qwe', 1, '1953-02-08', 2, 'AbbieByrd575@example.com', '(657) 833-1674', '2815 Mountain Hwy, Suite 82, Dover, Delaware, 78592', 'be106bac-b4d7-11ed-8178-40167e258f11', 'be106bb2-b4d7-11ed-8178-40167e258f11', 'be106bb5-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:39', 'Denis Cardwell', '2002-09-04 20:21:22', 'Andy Gonzales', 3850, 0),
('6d5cc407-7288-2823-55cb-b8d37b68af4d', '3', 'Tomas2002', 'Teofila65', '123qwe', 0, '1955-06-11', 1, 'AmadoMedina589@example.com', '(533) 039-4249', '1998 Cedar Tree Lane, STE 9822, Denver, CO, 19127', 'be106c5e-b4d7-11ed-8178-40167e258f11', 'be106c63-b4d7-11ed-8178-40167e258f11', 'be106c67-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:14:52', 'Joye Ryder', '1970-01-01 00:23:34', 'Shirlee Healy', -8, 0),
('6fcbca4a-7938-4339-51cb-b8d37b68af4d', '2', 'Tania597', 'English2017', '123qwe', 1, '1994-04-06', 1, 'Babin@example.com', '(730) 273-6683', '758 Flintwood Hwy, Juneau, Alaska, 88655', 'be106dfa-b4d7-11ed-8178-40167e258f11', 'be106e00-b4d7-11ed-8178-40167e258f11', 'be106e04-b4d7-11ed-8178-40167e258f11', '1984-11-17 09:18:57', 'Karly Aguirre', '1979-08-24 18:08:50', 'Lyndsay Biggs', -1186503570, 0),
('6fe7520c-5758-2461-3a69-9f77bda75690', '384YV', 'Mccann2018', 'Snell1964', '123qwe', 0, '1953-11-01', 2, NULL, '(866) 682-6586', '128 East Monument Ct, Charleston, West Virginia, 26086', 'be106f1e-b4d7-11ed-8178-40167e258f11', 'be106f24-b4d7-11ed-8178-40167e258f11', 'be106f28-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:05:05', 'Alexis Goulet', '1970-01-01 00:07:49', 'Myles Gatewood', -30, 0),
('70edc7b9-702f-70b2-3d71-153b37881afe', 'XV9NDB', 'Crocker2021', 'Bernardo1957', '123qwe', 0, NULL, 2, 'StephaniJ_Grossman@example.com', NULL, NULL, 'be106fdd-b4d7-11ed-8178-40167e258f11', 'be106fe2-b4d7-11ed-8178-40167e258f11', 'be106fe6-b4d7-11ed-8178-40167e258f11', NULL, NULL, '1991-11-26 00:16:57', 'Andrew Quinonez', NULL, 0),
('724a3873-137c-6563-3a95-2c566fa88632', 'HT7Q1NU3G045', 'Keck1972', 'Toledo921', '123qwe', 1, '1989-05-09', 2, 'enqvjfmk.cofgkn@nowhere.com', '(610) 362-5075', '44 W Prospect Hill Street, Comcast Bldg, Columbus, OH, 61722', 'be10708f-b4d7-11ed-8178-40167e258f11', 'be107094-b4d7-11ed-8178-40167e258f11', 'be107098-b4d7-11ed-8178-40167e258f11', '2017-03-21 07:33:15', 'Agueda Camp', '1996-05-19 04:01:16', 'Cristy Andre', -2007552699, 0),
('751d9b3c-4512-268d-2826-978952f080e4', '9', 'Garland5', 'Ahmed2026', '123qwe', 0, '1954-07-02', 0, 'Frankie_Grossman@nowhere.com', '(535) 013-0514', '110 North Rose Hill St, Providence, RI, 49064', 'be107147-b4d7-11ed-8178-40167e258f11', 'be10714c-b4d7-11ed-8178-40167e258f11', 'be10714f-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:09:08', 'Vita Morrissey', '1998-05-09 07:31:18', 'Felicidad Lentz', -5, 0),
('77f9db4f-5327-23f3-2b26-978952f080e4', 'W6V', 'Galvan2023', 'Gino2003', '123qwe', 0, '1980-03-25', 0, 'kfuiwqi0177@example.com', '(218) 624-3450', '455 E Fox Hill Parkway, Guardian Bldg, Bismarck, North Dakota, 52908', 'be1071f5-b4d7-11ed-8178-40167e258f11', 'be1071fa-b4d7-11ed-8178-40167e258f11', 'be1071fe-b4d7-11ed-8178-40167e258f11', '2007-04-08 05:13:35', 'Christeen Acker', '1970-01-01 00:00:02', 'Ada Ackerman', -1704527747, 0),
('794ca02a-1314-6ec3-df69-4afe230d73a5', '2Y', 'Lawrence8', 'Andreas1980', '123qwe', 0, '1953-01-03', 0, 'Rosario_Dejesus7@example.com', '(247) 811-3933', '1083 NE Hazelwood Pkwy, Judge Bldg, Atlanta, Georgia, 36014', 'be1072ae-b4d7-11ed-8178-40167e258f11', 'be1072b3-b4d7-11ed-8178-40167e258f11', 'be1072b7-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:00:03', 'Andrew Crutchfield', '2000-10-14 20:07:58', 'Gale Maldonado', 23, 0),
('79c13594-4781-1b7c-204a-aea48a10ed18', 'CZ9W09I', 'Antony98', 'Stefan547', '123qwe', 1, '1981-05-17', 1, 'GiannaJenkins@example.com', '(438) 866-0472', '131 Fox Hill Lane, Raleigh, NC, 98744', 'be10735c-b4d7-11ed-8178-40167e258f11', 'be107361-b4d7-11ed-8178-40167e258f11', 'be107364-b4d7-11ed-8178-40167e258f11', '1977-11-12 05:55:02', 'Duncan Sisco', '2006-07-24 14:16:11', 'Allan Whittaker', -851309381, 0),
('7a7d008f-16e6-64f9-234a-aea48a10ed18', 'S7DROE92LO08J', 'Adalberto972', 'Frey2003', '123qwe', 1, '1953-04-08', 2, 'Clapp@example.com', '(153) 734-4222', '61 Church Ct, Victor Executive Bldg, Austin, TX, 58563', 'be10741a-b4d7-11ed-8178-40167e258f11', 'be107420-b4d7-11ed-8178-40167e258f11', 'be107424-b4d7-11ed-8178-40167e258f11', '1970-01-01 00:01:38', 'Adolfo Rangel', '1978-07-07 00:54:38', 'Latosha Covey', 978, 0),
('7e336cda-7f4c-3a8e-3895-2c566fa88632', '6', 'Clary2024', 'Milford9', '123qwe', 0, '1971-10-02', 0, 'Rau71@nowhere.com', '(552) 037-7186', '822 Prospect Hill Highway, Juneau, AK, 48124', 'be1074ca-b4d7-11ed-8178-40167e258f11', 'be1074d0-b4d7-11ed-8178-40167e258f11', 'be1074d3-b4d7-11ed-8178-40167e258f11', '1979-05-29 11:26:47', 'Lester Cohn', '1976-03-29 03:32:31', 'Carylon Mintz', -1181469310, 0),
('7f2f326b-4385-3beb-244a-aea48a10ed18', 'GRPI32O53I', 'Holland2015', 'Morris2029', '123qwe', 0, '1980-06-06', 2, 'AndrusZ@example.com', '(367) 989-4000', '1431 East Lake Loop, Hartford, Connecticut, 56534', 'be107575-b4d7-11ed-8178-40167e258f11', 'be10757a-b4d7-11ed-8178-40167e258f11', 'be10757e-b4d7-11ed-8178-40167e258f11', '2017-04-09 01:18:53', 'Delmy Peeler', '1970-01-01 00:59:28', 'Abdul Hudson', -1634708498, 0),
('7fc94edc-2827-7327-1f1e-21c6d80fbd76', 'IUATN3NYNB1J842', 'Mac2024', 'Jewel535', '123qwe', 0, '1982-01-28', 1, 'Costa@example.com', '(961) 069-2786', '253 Sharp Hill Dr, Annapolis, MD, 34354', 'be107621-b4d7-11ed-8178-40167e258f11', 'be107626-b4d7-11ed-8178-40167e258f11', 'be10762a-b4d7-11ed-8178-40167e258f11', '1977-01-30 02:56:55', 'Dudley Rowan', '1970-01-01 00:15:23', 'Hailey Cardwell', -668870769, 0),
('d728c751-a857-43ab-9748-243f6aa4f22e', 'test', 'test', 'test', '123qwe', 1, NULL, 1, 'test@gmail.com', '09843', NULL, NULL, NULL, NULL, '2023-02-25 16:45:20', NULL, '2023-02-25 16:45:26', NULL, 0, 0);

-- 
-- Dumping data for table databaseinfo
--
-- Table qvc_task_info.databaseinfo does not contain any data (it is empty)

-- 
-- Dumping data for table company
--
INSERT INTO company VALUES
('1ccc117c-8ed6-45e6-aee4-f320af90fa50', 'CP22561', 'Ahjidfjfgldlgfhfghfgh', 'test2', '2023-02-26 18:51:38', NULL, '2023-02-26 18:51:38', NULL),
('1e362de1-7b1f-4868-b821-1c04db0e361d', 'CP34352', 'AAAAAAAAAAAAA', 'test2', '2023-02-26 18:42:15', NULL, '2023-02-26 18:42:15', NULL),
('4d0b8791-73c4-4492-b3f0-2cab5de2a618', 'CP93640', 'Công ty này ok', 'test', '2023-02-25 16:52:15', NULL, '2023-02-25 16:52:15', NULL),
('516f2f88-fe3f-4ffc-99ff-f9aba532fdd0', 'CP17008', 'dsfdsgsdg', 'quachcanh', '2023-02-25 16:22:33', NULL, '2023-02-25 16:22:33', NULL),
('72b68714-fc43-4108-adff-b03089541dd6', 'CP81631', 'sdgssdf', 'quachcanh', '2023-02-25 15:59:49', NULL, '2023-02-25 15:59:49', NULL),
('82c5869d-5465-41e8-a408-358a60160189', 'CP93593', 'Ctykfđf', 'quachcanh', '2023-02-25 15:39:03', NULL, '2023-02-25 15:39:03', NULL),
('8a4d0aa7-ba28-4222-b5ab-0283a4f8bebe', 'CP46211', 'Công Ty của Test 2', 'test2', '2023-02-26 18:34:27', NULL, '2023-02-26 18:34:27', NULL),
('a02f02ae-ff89-4a48-bd01-577024284686', 'CP82272', 'dgsdgsdgsd', 'quachcanh', '2023-02-25 15:38:47', NULL, '2023-02-25 15:38:47', NULL),
('a6fe0415-bc33-4689-8344-d9e1975c6b2e', 'CP90165', 'Ctykfđfdf', 'quachcanh', '2023-02-25 15:39:42', NULL, '2023-02-25 15:39:42', NULL),
('a854ef04-6b48-426f-bb24-01097eaad3a4', 'CP81112', 'Côgn Ty QVC', 'quachcanh', '2023-02-25 15:14:28', NULL, '2023-02-25 15:14:28', NULL),
('ba752a4e-54f9-4583-9d36-5728d90b953c', 'CP34671', 'Công Ty Test 1', 'test', '2023-02-25 16:46:29', NULL, '2023-02-25 16:46:29', NULL),
('bb29d5ce-ebde-4781-8d68-56d6b00acea9', 'CP61391', 'công ty abgn', 'test2', '2023-02-26 18:41:06', NULL, '2023-02-26 18:41:06', NULL),
('c5c6b19d-166d-4325-8932-a482e9e8a437', 'CP54373', 'Công ty ABC', 'test', '2023-02-26 21:58:10', NULL, '2023-02-26 21:58:10', NULL),
('dff7e8f7-cb7a-4ef4-a000-87c1a8a679b7', 'CP71326', '123qwewesd', 'quachcanh', '2023-02-25 16:14:43', NULL, '2023-02-25 16:14:43', NULL),
('e3e03c92-b736-4073-9f6a-8a0f88171d66', 'CP26832', 'dsf546', 'quachcanh', '2023-02-25 16:05:07', NULL, '2023-02-25 16:05:07', NULL),
('f8e0d15c-c05b-449f-969c-56ab2a7d0aaa', 'CP17627', '123qwewe', 'quachcanh', '2023-02-25 16:14:27', NULL, '2023-02-25 16:14:27', NULL),
('fcced88a-3fbb-4b6d-8a13-bc6a0d4d7993', 'CP59983', 'AhihiHaha', 'test2', '2023-02-26 18:48:34', NULL, '2023-02-26 18:48:34', NULL),
('fe4d674f-aa57-45d9-bbe2-9ef391a3135d', 'CP66706', 'dgsdgsdg', 'quachcanh', '2023-02-25 15:38:27', NULL, '2023-02-25 15:38:27', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;